# Generated by Django 3.1.3 on 2021-03-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210321_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
