# Generated by Django 3.1.3 on 2021-04-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaimages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='text',
        ),
        migrations.AddField(
            model_name='image',
            name='remote_id',
            field=models.CharField(default='123456789', max_length=255),
        ),
    ]
