# Generated by Django 3.1.3 on 2021-04-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captchaimages', '0002_auto_20210405_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
