# Generated by Django 3.1.3 on 2021-04-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaimages', '0004_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='remote_url',
            field=models.URLField(default='image'),
        ),
    ]
