# Generated by Django 3.1.3 on 2021-05-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captchaimages', '0006_auto_20210424_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
